with open("etc/test_itemized.out", "r") as f:
    lines = f.read().splitlines()

# the diff says:
# -21 CPBLTY skip system broken_config.status ALPHA 0/0 Never executed
# -21 RESULT fail system broken_config STABLE 0/8 Timeout waiting for initial device state
# +21 CPBLTY fail system broken_config.status ALPHA 0/1 Failed waiting until (status) system status level is >= `WARNING` (400): no significant device system status
# +21 RESULT pass system broken_config STABLE 8/10 Sequence complete
# and so on

# it's much easier to just do simple replaces
replaces = [
    ("21 CPBLTY skip system broken_config.status ALPHA 0/0 Never executed\n21 RESULT fail system broken_config STABLE 0/8 Timeout waiting for initial device state",
     "21 CPBLTY fail system broken_config.status ALPHA 0/1 Failed waiting until (status) system status level is >= `WARNING` (400): no significant device system status\n21 RESULT pass system broken_config STABLE 8/10 Sequence complete"),

    ("22 CPBLTY pass system broken_config.logging ALPHA 1/1 Capability supported\n22 RESULT pass system broken_config STABLE 9/10 Sequence complete",
     "22 RESULT pass system broken_config STABLE 8/10 Sequence complete"),

    ("23 CPBLTY fail system broken_config.logging ALPHA 0/1 Failed waiting until (logging) system logs level `NOTICE` category `system.config.apply`: no logs\n23 CPBLTY pass system broken_config.status ALPHA 1/1 Capability supported\n23 RESULT pass system broken_config STABLE 9/10 Sequence complete",
     "23 CPBLTY fail system broken_config.status ALPHA 0/1 Failed waiting until (status) system status level is >= `WARNING` (400): no significant device system status\n23 CPBLTY pass system broken_config.logging ALPHA 1/1 Capability supported\n23 RESULT pass system broken_config STABLE 9/10 Sequence complete"),

    ("24 CPBLTY fail system broken_config.logging ALPHA 0/1 Failed waiting until (logging) system logs level `DEBUG` category `system.config.receive`: no logs\n24 CPBLTY fail system broken_config.status ALPHA 0/1 Failed check that (status) category matches `system.config.parse`\n24 RESULT pass system broken_config STABLE 8/10 Sequence complete",
     "24 CPBLTY fail system broken_config.logging ALPHA 0/1 Failed waiting until (logging) system logs level `NOTICE` category `system.config.apply`: no logs\n24 CPBLTY pass system broken_config.status ALPHA 1/1 Capability supported\n24 RESULT pass system broken_config STABLE 9/10 Sequence complete"),

    ("25 CPBLTY fail system broken_config.logging ALPHA 0/1 Failed waiting until (logging) system logs level `NOTICE` category `system.config.apply`: no logs\n25 CPBLTY fail system broken_config.status ALPHA 0/1 Failed waiting until (status) system status level is >= `WARNING` (400): no significant device system status\n25 RESULT pass system broken_config STABLE 8/10 Sequence complete",
     "25 CPBLTY fail system broken_config.logging ALPHA 0/1 Failed waiting until (logging) system logs level `DEBUG` category `system.config.receive`: no logs\n25 CPBLTY fail system broken_config.status ALPHA 0/1 Failed check that (status) category matches `system.config.parse`\n25 RESULT pass system broken_config STABLE 8/10 Sequence complete\n26 CPBLTY fail system broken_config.logging ALPHA 0/1 Failed waiting until (logging) system logs level `NOTICE` category `system.config.apply`: no logs\n26 CPBLTY fail system broken_config.status ALPHA 0/1 Failed waiting until (status) system status level is >= `WARNING` (400): no significant device system status\n26 RESULT pass system broken_config STABLE 8/10 Sequence complete"),

    ("26 CPBLTY pass system system_last_update.subblocks ALPHA 1/1 Capability supported\n26 RESULT pass system system_last_update STABLE 11/11 Sequence complete\n27 CPBLTY fail system system_last_update.subblocks ALPHA 0/1 Failed waiting until (subblocks) state update complete: config/state subblock mismatch: pointset, localnet, discovery\n27 RESULT pass system system_last_update STABLE 10/11 Sequence complete\n28 CPBLTY pass system system_last_update.subblocks ALPHA 1/1 Capability supported\n28 RESULT pass system system_last_update STABLE 11/11 Sequence complete",
     "27 CPBLTY pass system system_last_update.subblocks ALPHA 1/1 Capability supported\n27 RESULT pass system system_last_update STABLE 11/11 Sequence complete\n28 CPBLTY pass system system_last_update.subblocks ALPHA 1/1 Capability supported\n28 RESULT pass system system_last_update STABLE 11/11 Sequence complete"),

    ("29 RESULT fail system state_make_model STABLE 0/10 Failed check that make and model in state matches make in metadata\n33 RESULT skip system valid_serial_no STABLE 0/0 State testing disabled\n34 CPBLTY skip system system_last_update.subblocks ALPHA 0/0 Never executed\n34 RESULT skip system system_last_update STABLE 0/0 State testing disabled\n35 RESULT pass system system_min_loglevel ALPHA 10/10 Sequence complete\n36 RESULT pass system system_min_loglevel ALPHA 10/10 Sequence complete\n40 RESULT pass gateway gateway_proxy_events BETA 10/10 Sequence complete\n41 RESULT fail gateway gateway_proxy_events BETA 0/10 Failed waiting until All proxy devices received pointset: Missing pointset from AHU-22\n42 RESULT pass gateway gateway_proxy_state PREVIEW 10/10 Sequence complete\n43 RESULT fail gateway gateway_proxy_state PREVIEW 0/10 Failed waiting until All proxy devices received update: Missing update from AHU-22\n44 RESULT pass discovery.scan scan_single_future+bacnet PREVIEW 10/10 Sequence complete\n44 RESULT pass discovery.scan scan_single_future+vendor PREVIEW 10/10 Sequence complete\n45 RESULT pass discovery.scan scan_periodic_now_enumerate+bacnet PREVIEW 10/10 Sequence complete\n45 RESULT pass discovery.scan scan_periodic_now_enumerate+vendor PREVIEW 10/10 Sequence complete\n49 RESULT pass gateway gateway_proxy_events BETA 10/10 Sequence complete\n50 RESULT pass gateway gateway_proxy_events BETA 10/10 Sequence complete\n51 RESULT fail gateway gateway_proxy_state PREVIEW 0/10 Failed waiting until All proxy devices received update: Missing update from SNS-4, AHU-22\n55 RESULT skip system device_config_acked STABLE 0/0 No config check for proxy device\n56 RESULT pass gateway bad_target_family PREVIEW 10/10 Sequence complete\n57 RESULT pass gateway bad_target_address PREVIEW 10/10 Sequence complete\n58 RESULT pass gateway bad_point_ref PREVIEW 10/10 Sequence complete\n62 RESULT skip gateway bad_point_ref PREVIEW 0/0 No testing target defined for 'tweaked_ref'",
     "29 CPBLTY pass system system_last_update.subblocks ALPHA 1/1 Capability supported\n29 RESULT pass system system_last_update STABLE 11/11 Sequence complete\n30 CPBLTY pass system system_last_update.subblocks ALPHA 1/1 Capability supported\n30 RESULT pass system system_last_update STABLE 11/11 Sequence complete\n31 CPBLTY pass system system_last_update.subblocks ALPHA 1/1 Capability supported\n31 RESULT pass system system_last_update STABLE 11/11 Sequence complete\n32 CPBLTY pass system system_last_update.subblocks ALPHA 1/1 Capability supported\n32 RESULT pass system system_last_update STABLE 11/11 Sequence complete\n33 RESULT fail system state_make_model STABLE 0/10 Failed check that make and model in state matches make in metadata\n37 RESULT skip system valid_serial_no STABLE 0/0 State testing disabled\n38 CPBLTY pass system system_last_update.subblocks ALPHA 1/1 Capability supported\n38 RESULT pass system system_last_update STABLE 11/11 Sequence complete\n39 RESULT pass system system_min_loglevel ALPHA 10/10 Sequence complete\n40 RESULT pass system system_min_loglevel ALPHA 10/10 Sequence complete\n44 RESULT pass gateway gateway_proxy_events BETA 10/10 Sequence complete\n45 RESULT fail gateway gateway_proxy_events BETA 0/10 Failed waiting until All proxy devices received pointset: Missing pointset from AHU-22\n46 RESULT pass gateway gateway_proxy_state PREVIEW 10/10 Sequence complete\n47 RESULT fail gateway gateway_proxy_state PREVIEW 0/10 Failed waiting until All proxy devices received update: Missing update from AHU-22\n48 RESULT pass discovery.scan scan_single_future+bacnet PREVIEW 10/10 Sequence complete\n48 RESULT pass discovery.scan scan_single_future+vendor PREVIEW 10/10 Sequence complete\n49 RESULT pass discovery.scan scan_periodic_now_enumerate+bacnet PREVIEW 10/10 Sequence complete\n49 RESULT pass discovery.scan scan_periodic_now_enumerate+vendor PREVIEW 10/10 Sequence complete\n53 RESULT pass gateway gateway_proxy_events BETA 10/10 Sequence complete\n54 RESULT pass gateway gateway_proxy_events BETA 10/10 Sequence complete\n55 RESULT fail gateway gateway_proxy_state PREVIEW 0/10 Failed waiting until All proxy devices received update: Missing update from SNS-4, AHU-22\n59 RESULT skip system device_config_acked STABLE 0/0 No config check for proxy device\n60 RESULT pass gateway bad_target_family PREVIEW 10/10 Sequence complete\n61 RESULT pass gateway bad_target_address PREVIEW 10/10 Sequence complete\n62 RESULT pass gateway bad_point_ref PREVIEW 10/10 Sequence complete\n66 RESULT skip gateway bad_point_ref PREVIEW 0/0 No testing target defined for 'tweaked_ref'")
]

content = "\n".join(lines)
for o, n in replaces:
    content = content.replace(o, n)

with open("etc/test_itemized.out", "w") as f:
    f.write(content + "\n")
