with open("etc/schema_itemized.out", "r") as f:
    lines = f.read().splitlines()

replaces = [
    ("20 broken_config RESULT pass schemas device_state_stable STABLE 10/10 Schema validation passed\n20 broken_config RESULT pass schemas events_system_stable STABLE 10/10 Schema validation passed\n20 broken_config RESULT pass schemas state_update_stable STABLE 10/10 Schema validation passed\n21 broken_config\n22 broken_config RESULT pass schemas device_state_stable STABLE 10/10 Schema validation passed\n22 broken_config RESULT pass schemas events_system_stable STABLE 10/10 Schema validation passed\n22 broken_config RESULT pass schemas state_update_stable STABLE 10/10 Schema validation passed\n23 broken_config RESULT pass schemas device_state_stable STABLE 10/10 Schema validation passed\n23 broken_config RESULT pass schemas events_system_stable STABLE 10/10 Schema validation passed\n23 broken_config RESULT pass schemas state_update_stable STABLE 10/10 Schema validation passed\n24 broken_config RESULT pass schemas device_state_stable STABLE 10/10 Schema validation passed\n24 broken_config RESULT pass schemas events_system_stable STABLE 10/10 Schema validation passed\n24 broken_config RESULT pass schemas state_update_stable STABLE 10/10 Schema validation passed\n25 broken_config RESULT fail schemas events_system_stable STABLE 10/10 Schema violations found\n25 broken_config RESULT fail schemas state_update_stable STABLE 10/10 Schema violations found\n25 broken_config RESULT pass schemas device_state_stable STABLE 10/10 Schema validation passed",
    "20 broken_config RESULT pass schemas device_state_stable STABLE 10/10 Schema validation passed\n20 broken_config RESULT pass schemas events_system_stable STABLE 10/10 Schema validation passed\n20 broken_config RESULT pass schemas state_update_stable STABLE 10/10 Schema validation passed\n21 broken_config RESULT fail schemas events_system_stable STABLE 10/10 Schema violations found\n22 broken_config RESULT fail schemas state_update_stable STABLE 10/10 Schema violations found\n23 broken_config RESULT pass schemas device_state_stable STABLE 10/10 Schema validation passed\n24 broken_config RESULT pass schemas device_state_stable STABLE 10/10 Schema validation passed\n24 broken_config RESULT pass schemas events_system_stable STABLE 10/10 Schema validation passed\n24 broken_config RESULT pass schemas state_update_stable STABLE 10/10 Schema validation passed\n25 broken_config RESULT pass schemas events_system_stable STABLE 10/10 Schema validation passed\n25 broken_config RESULT pass schemas state_update_stable STABLE 10/10 Schema validation passed\n26 broken_config RESULT pass schemas device_state_stable STABLE 10/10 Schema validation passed\n26 broken_config RESULT pass schemas events_system_stable STABLE 10/10 Schema validation passed\n26 broken_config RESULT pass schemas state_update_stable STABLE 10/10 Schema validation passed\n27 broken_config RESULT fail schemas events_system_stable STABLE 10/10 Schema violations found\n27 broken_config RESULT fail schemas state_update_stable STABLE 10/10 Schema violations found\n27 broken_config RESULT pass schemas device_state_stable STABLE 10/10 Schema validation passed"),

    ("26 system_last_update RESULT fail schemas state_update_stable STABLE 10/10 Schema violations found\n26 system_last_update RESULT pass schemas device_state_stable STABLE 10/10 Schema validation passed\n26 system_last_update RESULT pass schemas events_system_stable STABLE 10/10 Schema validation passed\n27 system_last_update RESULT fail schemas device_state_stable STABLE 10/10 Schema violations found\n27 system_last_update RESULT pass schemas events_system_stable STABLE 10/10 Schema validation passed\n27 system_last_update RESULT pass schemas state_update_stable STABLE 10/10 Schema validation passed\n28 system_last_update RESULT fail schemas events_system_stable STABLE 10/10 Schema violations found\n28 system_last_update RESULT fail schemas state_update_stable STABLE 10/10 Schema violations found\n28 system_last_update RESULT pass schemas device_state_stable STABLE 10/10 Schema validation passed\n29 state_make_model\n33 valid_serial_no\n34 system_last_update\n35 system_min_loglevel RESULT fail schemas device_state_alpha ALPHA 10/10 Schema violations found\n35 system_min_loglevel RESULT pass schemas events_system_alpha ALPHA 10/10 Schema validation passed\n35 system_min_loglevel RESULT pass schemas state_update_alpha ALPHA 10/10 Schema validation passed\n36 system_min_loglevel RESULT pass schemas device_state_alpha ALPHA 10/10 Schema validation passed\n36 system_min_loglevel RESULT pass schemas events_system_alpha ALPHA 10/10 Schema validation passed\n40 gateway_proxy_events\n41 gateway_proxy_events\n42 gateway_proxy_state\n43 gateway_proxy_state\n44 scan_single_future\n45 scan_periodic_now_enumerate\n49 gateway_proxy_events\n50 gateway_proxy_events\n51 gateway_proxy_state\n55 device_config_acked\n56 bad_target_family\n57 bad_target_address\n58 bad_point_ref",
     "28 system_last_update RESULT fail schemas state_update_stable STABLE 10/10 Schema violations found\n28 system_last_update RESULT pass schemas device_state_stable STABLE 10/10 Schema validation passed\n28 system_last_update RESULT pass schemas events_system_stable STABLE 10/10 Schema validation passed\n29 system_last_update RESULT fail schemas device_state_stable STABLE 10/10 Schema violations found\n29 system_last_update RESULT pass schemas events_system_stable STABLE 10/10 Schema validation passed\n29 system_last_update RESULT pass schemas state_update_stable STABLE 10/10 Schema validation passed\n30 system_last_update RESULT fail schemas events_system_stable STABLE 10/10 Schema violations found\n30 system_last_update RESULT fail schemas state_update_stable STABLE 10/10 Schema violations found\n30 system_last_update RESULT pass schemas device_state_stable STABLE 10/10 Schema validation passed\n31 state_make_model\n35 valid_serial_no\n36 system_last_update RESULT fail schemas events_system_stable STABLE 10/10 Schema violations found\n37 system_last_update RESULT fail schemas state_update_stable STABLE 10/10 Schema violations found\n38 system_last_update RESULT pass schemas device_state_stable STABLE 10/10 Schema validation passed\n39 system_min_loglevel RESULT fail schemas device_state_alpha ALPHA 10/10 Schema violations found\n39 system_min_loglevel RESULT pass schemas events_system_alpha ALPHA 10/10 Schema validation passed\n39 system_min_loglevel RESULT pass schemas state_update_alpha ALPHA 10/10 Schema validation passed\n40 system_min_loglevel RESULT pass schemas device_state_alpha ALPHA 10/10 Schema validation passed\n40 system_min_loglevel RESULT pass schemas events_system_alpha ALPHA 10/10 Schema validation passed\n44 gateway_proxy_events\n45 gateway_proxy_events\n46 gateway_proxy_state\n47 gateway_proxy_state\n48 scan_single_future\n49 scan_periodic_now_enumerate\n53 gateway_proxy_events\n54 gateway_proxy_events\n55 gateway_proxy_state\n59 device_config_acked\n60 bad_target_family\n61 bad_target_address\n62 bad_point_ref\n66 bad_point_ref")
]

content = "\n".join(lines)
for o, n in replaces:
    content = content.replace(o, n)

with open("etc/schema_itemized.out", "w") as f:
    f.write(content + "\n")
