import os
from pathlib import Path

def ingest_logs(local_dir=None, is_ci=False, _internal_retry=False):
    """
    Fetch log files from local directory or CI environment.
    Includes golden files if available to provide baseline context,
    as well as MQTT logs and specific out files generated by test_itemized, test_sequencer, etc.
    """
    logs = {}

    # Ingest golden files from etc/ directory (only on initial call, not retries)
    if not _internal_retry and os.path.exists('etc'):
        print("Ingesting golden context from etc/...")
        for root, dirs, files in os.walk('etc'):
            for file in files:
                if file.endswith('.out') or file.endswith('.json') or file.endswith('.txt'):
                    filepath = os.path.join(root, file)
                    try:
                        with open(filepath, 'r', encoding='utf-8') as f:
                            logs[filepath] = f.readlines()
                    except Exception as e:
                        print(f"Failed to read {filepath}: {e}")

    # Ingest from mosquitto logs if accessible
    mosquitto_log_path = "/var/log/mosquitto/mosquitto.log"
    if not _internal_retry and os.path.exists(mosquitto_log_path):
        try:
             with open(mosquitto_log_path, 'r', encoding='utf-8') as f:
                 logs[mosquitto_log_path] = f.readlines()
        except Exception as e:
             print(f"Failed to read {mosquitto_log_path}: {e}")

    # Primary ingestion from target out directories
    if local_dir:
        base_path = Path(local_dir)
        for root, dirs, files in os.walk(base_path):
            for file in files:
                # We want to capture .log, .out, specific captures, test failures
                if (file.endswith(".log") or
                    file.endswith(".out") or
                    "test_failures" in file or
                    file == "message_capture.log"):

                    filepath = os.path.join(root, file)
                    try:
                        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
                            logs[filepath] = f.readlines()
                    except Exception as e:
                        print(f"Failed to read {filepath}: {e}")

    elif is_ci:
        print("CI mode active. Falling back to local 'out' directory for logs.")
        # Attempt to read 'out' directory
        return ingest_logs(local_dir="out", is_ci=False, _internal_retry=True)

    return logs
