listener 8883
cafile /usr/local/google/home/heykhyati/Projects/udmi/clientlib/python/local_testing/certs/ca.crt
certfile /usr/local/google/home/heykhyati/Projects/udmi/clientlib/python/local_testing/certs/server.crt
keyfile /usr/local/google/home/heykhyati/Projects/udmi/clientlib/python/local_testing/certs/server.key

require_certificate true

use_identity_as_username true